<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ChauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChauffeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchChauffeurs($search,$id,$tri)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Chauffeur m where m.nom like :motcle and m.jardin=:id order by m.nom ".$tri)
            ->setParameter('motcle','%'.$search.'%')
        ->setParameter('id',$id);
        return $query=$q->getResult();

    }
}
