<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchEvents($search,$id)
{
    $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Evenement m where m.titre like :motcle and m.jardin=:id")
        ->setParameter('motcle','%'.$search.'%')
        ->setParameter('id',$id);
    return $query=$q->getResult();

}

    public function getEvenement($id)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m.id , m.titre , m.description, m.date, c.libelle from AppBundle:Evenement m , AppBundle:Categorie c where m.categorie=c.id and m.id=:id")
            ->setParameter('id',$id);

        return $query=$q->getResult();

    }


    public function evenement($id){
        $q=$this->getEntityManager()->createQuery("SELECT m.id  from AppBundle:Evenement m  where  m.id=:id")
            ->setParameter('id',$id);

        return $query=$q->getResult();

    }
}
