<?php

namespace AppBundle\Repository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParent($id)
    {
        $q=$this->getEntityManager()->createQuery("Select p.nom,p.prenom,p.numtel,p.adresse  from AppBundle:Parents p where 
        p.id=:id ")
            ->setParameter('id',$id);
        return $query=$q->getResult();



    }


}
