<?php

namespace AppBundle\Repository;

/**
 * TuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchTuteurs($search,$id,$tri)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Tuteur m where (m.nom like :motcle or m.prenom like :motcle) and m.jardin=:id order by m.nom ".$tri)
            ->setParameter('motcle','%'.$search.'%')
            ->setParameter('id',$id);
        return $query=$q->getResult();

    }
}
