<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsername($username)
    {
        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:User m where m.username=:us ")->setParameter("us",$username);

        return $query=$q->getResult();
    }


    public function testuser($username,$email)
    {
        $q=$this->getEntityManager()->createQuery("Select u.id ,u.username,u.email from AppBundle:User u where 
        u.username=:username OR u.email=:email ")
            ->setParameter('username',$username)->setParameter("email",$email);
        return $query=$q->getResult();



    }


    public function finduser($username)
    {

        //get user credentials


        $q = $this->getEntityManager()
            ->createQuery("SELECT  u.id, u.username, u.email, u.roles, (case when u.roles like '%PARENT%' then 'P'
            when u.roles like '%RESPONSABLE%' then 'R'
            when u.roles like '%TUTEUR%' then 'T'
            when u.roles like '%CHAUFFEUR%' then 'C'
             ELSE 0 END) AS type   from AppBundle:User u where u.username=:username ")
            ->setParameter('username', $username);

       $query = $q->getResult();
        return $query;
    }

    }
