<?php

namespace SamiBundle\Controller;

use AppBundle\Entity\Chauffeur;
use SamiBundle\Form\ChauffeurType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

/**
 * Chauffeur controller.
 *
 * @Route("chauffeur")
 */
class ChauffeurController extends Controller
{
    /**
     * Lists all chauffeur entities.
     *
     * @Route("/", name="chauffeur_index")
     * @Method("GET")
     */
    public function indexAction(Request $request)
    {        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        $em = $this->getDoctrine()->getManager();

        $chauffeurs = $em->getRepository(Chauffeur::class)->findBy(array('jardin'=>$user->getJardin()));

        if($request->isMethod("post"))
{
$chauffeurs=$em->getRepository(Chauffeur::class)->searchChauffeurs($request->get('search'),$user->getJardin(),$request->get('tri'));
}

        return $this->render('@Sami/chauffeur/index.html.twig', array(
            'chauffeurs' => $chauffeurs,
        ));
    }

    /**
     * Creates a new chauffeur entity.
     *
     * @Route("/new", name="chauffeur_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $user = $this->container->get('security.token_storage')->getToken()->getUser();

        $chauffeur = new Chauffeur();
        $form = $this->createForm(ChauffeurType::class, $chauffeur);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $chauffeur->addRole("ROLE_Chauffeur");
            $chauffeur->setJardin($user->getJardin());
            $em = $this->getDoctrine()->getManager();
            $em->persist($chauffeur);
            $em->flush();
            return $this->redirectToRoute('chauffeur_show', array('id' => $chauffeur->getId()));
        }

        return $this->render('@Sami/chauffeur/new.html.twig', array(
            'chauffeur' => $chauffeur,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a chauffeur entity.
     *
     * @Route("/{id}", name="chauffeur_show")
     * @Method("GET")
     */
    public function showAction(Chauffeur $chauffeur)
    {
        $deleteForm = $this->createDeleteForm($chauffeur);

        return $this->render('@Sami/chauffeur/show.html.twig', array(
            'chauffeur' => $chauffeur,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing chauffeur entity.
     *
     * @Route("/{id}/edit", name="chauffeur_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Chauffeur $chauffeur)
    {
        $deleteForm = $this->createDeleteForm($chauffeur);
        $editForm = $this->createForm(ChauffeurType::class, $chauffeur);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() ) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('chauffeur_edit', array('id' => $chauffeur->getId()));
        }

        return $this->render('@Sami/chauffeur/edit.html.twig', array(
            'chauffeur' => $chauffeur,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a chauffeur entity.
     *
     * @Route("/delete/{id}", name="chauffeur_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Chauffeur $chauffeur)
    {

        $form = $this->createDeleteForm($chauffeur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($chauffeur);
            $em->flush();
        }

        return $this->redirectToRoute('chauffeur_index');
    }

    /**
     * Creates a form to delete a chauffeur entity.
     *
     * @param Chauffeur $chauffeur The chauffeur entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Chauffeur $chauffeur)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('chauffeur_delete', array('id' => $chauffeur->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
    private function generateUniqueFileName()
    {

        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
